[2021-11-22 13:24:46,459] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ELT-python-snowflake.Extract manual__2021-11-22T13:24:45.114952+00:00 [queued]>
[2021-11-22 13:24:46,504] {taskinstance.py:1035} INFO - Dependencies all met for <TaskInstance: ELT-python-snowflake.Extract manual__2021-11-22T13:24:45.114952+00:00 [queued]>
[2021-11-22 13:24:46,507] {taskinstance.py:1241} INFO - 
--------------------------------------------------------------------------------
[2021-11-22 13:24:46,516] {taskinstance.py:1242} INFO - Starting attempt 1 of 1
[2021-11-22 13:24:46,521] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2021-11-22 13:24:46,570] {taskinstance.py:1262} INFO - Executing <Task(BashOperator): Extract> on 2021-11-22 13:24:45.114952+00:00
[2021-11-22 13:24:46,593] {standard_task_runner.py:52} INFO - Started process 2733 to run task
[2021-11-22 13:24:46,611] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'ELT-python-snowflake', 'Extract', 'manual__2021-11-22T13:24:45.114952+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/ELT-python-snowflake.py', '--cfg-path', '/tmp/tmpync2l351', '--error-file', '/tmp/tmp34po0f0q']
[2021-11-22 13:24:46,642] {standard_task_runner.py:77} INFO - Job 72: Subtask Extract
[2021-11-22 13:24:46,730] {logging_mixin.py:109} INFO - Running <TaskInstance: ELT-python-snowflake.Extract manual__2021-11-22T13:24:45.114952+00:00 [running]> on host bd3f5d3b0fb3
[2021-11-22 13:24:46,880] {taskinstance.py:1429} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ELT-python-snowflake
AIRFLOW_CTX_TASK_ID=Extract
AIRFLOW_CTX_EXECUTION_DATE=2021-11-22T13:24:45.114952+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-22T13:24:45.114952+00:00
[2021-11-22 13:24:46,883] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2021-11-22 13:24:46,886] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'python3 /opt/***/elt/user-orders/extract-load/mysql_to_s3.py']
[2021-11-22 13:24:46,914] {subprocess.py:85} INFO - Output:
[2021-11-22 13:24:51,294] {subprocess.py:89} INFO - WARNING: An illegal reflective access operation has occurred
[2021-11-22 13:24:51,295] {subprocess.py:89} INFO - WARNING: Illegal reflective access by org.apache.spark.unsafe.Platform (file:/home/***/.local/lib/python3.7/site-packages/pyspark/jars/spark-unsafe_2.12-3.1.1.jar) to constructor java.nio.DirectByteBuffer(long,int)
[2021-11-22 13:24:51,297] {subprocess.py:89} INFO - WARNING: Please consider reporting this to the maintainers of org.apache.spark.unsafe.Platform
[2021-11-22 13:24:51,298] {subprocess.py:89} INFO - WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[2021-11-22 13:24:51,299] {subprocess.py:89} INFO - WARNING: All illegal access operations will be denied in a future release
[2021-11-22 13:24:51,887] {subprocess.py:89} INFO - 21/11/22 13:24:51 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2021-11-22 13:24:52,678] {subprocess.py:89} INFO - Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
[2021-11-22 13:24:52,681] {subprocess.py:89} INFO - Setting default log level to "WARN".
[2021-11-22 13:24:52,684] {subprocess.py:89} INFO - To adjust logging level use sc.setLogLevel(newLevel). For SparkR, use setLogLevel(newLevel).
[2021-11-22 13:25:09,911] {subprocess.py:89} INFO - [Stage 0:>                                                          (0 + 1) / 1]                                                                                /home/***/.local/lib/python3.7/site-packages/snowflake/connector/options.py:97: UserWarning: You have an incompatible version of 'pyarrow' installed (4.0.1), please install a version that adheres to: 'pyarrow<5.1.0,>=5.0.0; extra == "pandas"'
[2021-11-22 13:25:09,913] {subprocess.py:89} INFO -   _expected_pyarrow_version,
[2021-11-22 13:25:09,915] {subprocess.py:89} INFO - uploading entity: USERS
[2021-11-22 13:25:09,917] {subprocess.py:89} INFO - new:
[2021-11-22 13:25:09,918] {subprocess.py:89} INFO - +---+----+---+-------+----------+----------+
[2021-11-22 13:25:09,919] {subprocess.py:89} INFO - | id|name|age|address|created_at|updated_at|
[2021-11-22 13:25:09,920] {subprocess.py:89} INFO - +---+----+---+-------+----------+----------+
[2021-11-22 13:25:09,922] {subprocess.py:89} INFO - +---+----+---+-------+----------+----------+
[2021-11-22 13:25:09,923] {subprocess.py:89} INFO - 
[2021-11-22 13:25:09,924] {subprocess.py:89} INFO - uploading entity: ORDERS
[2021-11-22 13:25:09,925] {subprocess.py:89} INFO - new:
[2021-11-22 13:25:09,926] {subprocess.py:89} INFO - +---+-------+-----+------+----------+----------+
[2021-11-22 13:25:09,927] {subprocess.py:89} INFO - | id|id_user|spent|status|created_at|updated_at|
[2021-11-22 13:25:09,928] {subprocess.py:89} INFO - +---+-------+-----+------+----------+----------+
[2021-11-22 13:25:09,929] {subprocess.py:89} INFO - +---+-------+-----+------+----------+----------+
[2021-11-22 13:25:09,930] {subprocess.py:89} INFO - 
[2021-11-22 13:25:10,939] {subprocess.py:93} INFO - Command exited with return code 0
[2021-11-22 13:25:10,978] {taskinstance.py:1280} INFO - Marking task as SUCCESS. dag_id=ELT-python-snowflake, task_id=Extract, execution_date=20211122T132445, start_date=20211122T132446, end_date=20211122T132510
[2021-11-22 13:25:11,034] {local_task_job.py:154} INFO - Task exited with return code 0
[2021-11-22 13:25:11,089] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
